<?php
$title = 'Suppression du réalisateur';
$url   = $this->url('director', ['action' => 'delete', 'id' => $this->id]);
$this->headTitle($title);
?>

<h1>
    <?= $this->escapeHtml($title) ?>
</h1>

<p>
    Êtes-vous sûr de vouloir supprimer le réalisateur "<?= $this->escapeHtml($this->genre->getLabel()) ?>" (sur la liste hein, pas dans la vraie vie) ?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $this->director->getId() ?>"/>
        <input type="submit" name="del" class="btn btn-danger" value="Oui"/>
        <input type="submit" name="del" class="btn btn-success" value="Non"/>
    </div>
</form>
