<?php
$title = 'Ajouter un genre';
$this->headTitle($title);
?>

<h1>
    <?= $this->escapeHtml($title) ?>
</h1>

<?php
/** @var \Zend\Form\Form $genre */
$genre = $this->form->get('genre')->get('label');
$genre->setAttribute('class', 'form-control');
$genre->setAttribute('placeholder', 'Libelle');

/** @var \Zend\Form\Form $submit */
$submit = $this->form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$this->form->setAttribute('action', $this->url('genre', ['action' => 'add']));
$this->form->prepare();

echo $this->form()->openTag($this->form);
?>

<div class="form-group">
    <?= $this->formLabel($genre) ?>
    <?= $this->formElement($genre) ?>
    <?= $this->formElementErrors()->render($genre, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($this->form->get('genre')->get('id'));
echo $this->form()->closeTag();
