<?php
$title = 'Liste des genres';
$this->headTitle($title);
?>

<h1>
    <?= $this->escapeHtml($title) ?>
</h1>

<p>
    <a href="<?= $this->url('genre', ['action' => 'add']) ?>">
        Ajouter un genre
    </a>
</p>

<table class="table">
    <tr>
        <th>Libelle</th>
    </tr>
    <?php foreach($this->genres as $genre) : ?>
        <?php /** @var \Genre\Entity\Genre $genre */ ?>
        <tr>
            <td>
                <?= $this->escapeHtml($genre->getLabel()) ?>
            </td>
            <td>
                <a href="<?= $this->url('genre', ['action' => 'edit', 'id' => $genre->getId()]) ?>">Modifier</a>
                <a href="<?= $this->url('genre', ['action' => 'delete', 'id' => $genre->getId()]) ?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
