<?php
$title = 'Liste des films';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    <a href="<?= $this->url('film', ['action' => 'add']) ?>">Ajouter un film</a>
</p>

<table class="table">
    <tr>
        <th>Titre</th>
        <th>Genre</th>
        <th>Réalisateur</th>
        <th>Note</th>
        <th>Année</th>
        <th>Synopsis</th>
    </tr>
    <?php foreach($this->films as $film) : ?>
        <?php /** @var \Film\Entity\Film $film */ ?>
        <tr>
            <td><?= $this->escapeHtml($film->getTitle()) ?></td>
            <td><?= $this->escapeHtml($film->getGenre()->getLabel()) ?></td>
            <td><?= $this->escapeHtml($film->getDirector()->getFullname()) ?></td>
            <td><?= $this->escapeHtml($film->getNote()) ?></td>
            <td><?= $this->escapeHtml($film->getReleaseYear()) ?></td>
            <td><?= $this->escapeHtml($film->getSynopsis()) ?></td>
            <td>
                <a href="<?= $this->url('film', ['action' => 'edit', 'id' => $film->getId()]) ?>">Modifier</a>
                <a href="<?= $this->url('film', ['action' => 'delete', 'id' => $film->getId()]) ?>">Supprimer</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
